development: &default
  adapter: postgresql
  username: devaccount
  password: password
  database: cfg_dev
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: cfg_test
